# Generated by Django 2.2 on 2022-12-09 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_auto_20221208_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.School'),
        ),
    ]
