# Generated by Django 2.2 on 2022-12-13 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_profile_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='course_number',
        ),
    ]
