# Generated by Django 2.2 on 2022-12-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_auto_20221212_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(default='comment here'),
        ),
    ]
